micronaut:
  server:
    port: 8083
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  export:
    prometheus:
      enabled: true
      step: PT1M
      descriptions: true
#  router:
#    static-resources:
#      swagger:
#        enabled: true
#        mapping: /swagger/**
#        paths:
#          - classpath:META-INF/swagger
#
#      swagger-ui:
#        enabled: true
#        mapping: /swagger-ui/**
#        paths:
#          - classpath:META-INF/swagger/views/swagger-ui

endpoints:
  prometheus:
    sensitive: false


mongodb:
  uri: mongodb://localhost:27017/shopping-db

#redis:
#  uri: redis://localhost:6379
#  ssl: true
#  timeout: 30s
#  io-thread-pool-size: 5
#  computation-thread-pool-size: 4
#  caches:
#    products:
#      expire-after-write: 60s

kafka:
  bootstrap:
    servers: localhost:9092

  topic:
    start: start
    notify: notify

  consumer:
    group-id: shopping-group
    auto-offset-reset: latest

logger:
  levels:
    org.apache.kafka: OFF






