micronaut:
  server:
    port: 8086

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/inventory-db
    username: postgres
    password: 2503
    driver-class-name: org.postgresql.Driver
    dialect: io.micronaut.data.jdbc.postgres.PostgresDialect
    maximumPoolSize: 40
    minimumIdle: 10
    connectionTimeout: 30000
    idleTimeout: 10000
    autoCommit: true

jpa:
  default:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: update
    entity-scan:
      packages: com.inventory.core.models

kafka:
  bootstrap:
    servers: localhost:9092
  topic:
    orchestrator: orchestrator
    inventory-success: inventory-success
    inventory-fail: inventory-fail
  consumer:
    group-id: inventory-group
    auto-offset-reset: latest


logger:
  levels:
    org.apache.kafka: OFF
