micronaut:
  server:
    port: 8089

    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:3000
          allowed-methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
          allow-credentials: true

  security:
    enabled: true
    authentication: bearer

    intercept-url-map:
      - pattern: /api/v1/auth/**
        access:
          - isAnonymous()

      - pattern: /**
        access:
          - isAuthenticated()
  token:
    jwt:
      signatures:
        secret:
          generator:
            secret: "9f3c1a7b6d4e8f90a1c2b3d4e5f60718"

jwt:
  secret: "9f3c1a7b6d4e8f90a1c2b3d4e5f60718"

kafka:
  bootstrap:
    servers: localhost:9092
  topic:
    login: login

  consumer:
    group-id: login-group
    auto-offset-reset: latest

logger:
  levels:
    org.apache.kafka: OFF

datasources:
  default:
    url: jdbc:postgresql://localhost:5435/login-db
    username: postgres
    password: 2503
    driverClassName: org.postgresql.Driver
    dialect: io.micronaut.data.jdbc.postgres.PostgresDialect
    maximumPoolSize: 40
    minimumIdle: 10
    connectionTimeout: 30000
    idleTimeout: 10000
    autoCommit: true
jpa:
  default:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: update
    entity-scan:
      packages:
        - com.autorization.models.entity
